# Generated by Django 5.2.11 on 2026-02-26 16:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment',
            field=models.TextField(default=datetime.datetime(2026, 2, 26, 16, 25, 33, 622599, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
